.TH sigsegv_install_handler 3 "17 June 2021" "Solaris 11.4"
.SH NAME
sigsegv_install_handler, sigsegv_deinstall_handler - Install and deinstall a global SIGSEGV handler
.sp
.SH SYNOPSIS
.sp
#include <\fBsigsegv.h\fR>
.sp
int \fBsigsegv_install_handler\fR (\fIsigsegv_handler_t handler\fR);
.sp
void \fBsigsegv_deinstall_handler\fR (\fIvoid\fR);
.sp
.SH DESCRIPTION
.sp
.LP
Pageable virtual memory is usually done in the operating system's kernel. This library helps in implementing the others.
.sp
.LP
Installing a page fault handler is usually more efficient than doing access checks in software at every access, because it's effectively the hardware (the MMU) which checks whether a page is present or not.
.sp
.LP
Note that if you use system calls (like read()) to write into write-protected pages, the system will react by returning -1 and setting errno to EFAULT, instead of signalling SIGSEGV and restarting the system call. In this case, the program has to do what the SIGSEGV handler would do, and then restart the read() operation.
.sp
.LP
\fBSigsegv_install_handler\fR installs a global SIGSEGV handler. This should be called once only, and it ignores any previously installed SIGSEGV handler.
.sp
.LP
\fBSigsegv_deinstall_handler\fR deinstalls the global SIGSEGV handler. This goes back to the state where no SIGSEGV handler is installed.
.sp
.SH OPERANDS
.sp
.LP
typedef int (*\fBsigsegv_handler_t\fR) (\fIvoid* fault_address\fR,
.RS +34
\fIint serious\fR);
.RE
.sp
\fISigsegv_handler_t\fR is the type of a global SIGSEGV handler. The fault address is passed as an argument. The access type (read access or write access) is not passed; your handler has to know itself how to distinguish these two cases. If the second argument is 0, it means that it could also be a stack overflow, or 1, meaning the handler should seriously try to fix the fault. The return value should be nonzero if the handler has done its job and no other handler should be called, or 0 if the handler declines responsibility for the given address.
.sp
.LP
The handler is run at a moment when nothing about the global state of the program is known. Therefore it cannot use facilities that manipulate global variables or locks. In particular, it cannot use malloc(); use mmap() instead. It cannot use fopen(); use open() instead. Etc. All global variables that are accessed by the handler should be marked 'volatile'.
.sp
.SH EXIT STATUS
.sp
.LP
If success, sigsegv_install_handler returns 0, or -1 if the system doesn't support catching SIGSEGV.
.sp
.SH COPYRIGHT
Copyright 1998-1999, 2002-2012, 2016-2021  Bruno Haible <bruno@clisp.org>
.br
Copyright 2002-2005, 2009  Paolo Bonzini <bonzini@gnu.org>
.br
Copyright 2008-2010  Eric Blake <ebb9@byu.net>
.br
Copyright 2002-2021  Free Software Foundation, Inc.


GNU libsigsegv library and manual pages are licensed under GNU GPL version 2
or later <https://gnu.org/licenses/gpl\-2.0.html>. This is free software:
you are free to change and redistribute it. There is NO WARRANTY, to the
extent permitted by law.
.SH SEE ALSO
.sp
.LP
\fBattributes\fR(7), \fBsigsegv\fR(3), \fBstandards\fR(7)
