#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2018, 2019, Oracle and/or its affiliates. All rights reserved.
#

BUILD_BITS =            32
include ../../../../make-rules/shared-macros.mk

COMPONENT_NAME=		xtrans
COMPONENT_VERSION=	1.4.0
COMPONENT_ARCHIVE_HASH= \
	sha256:377c4491593c417946efcd2c7600d1e62639f7a8bbca391887e2c4679807d773
COMPONENT_BUGDB=        x11/libraries
COMPONENT_ANITYA_ID=	13441
TPNO=			50578

TEST_TARGET = $(NO_TESTS)

include $(WS_MAKE_RULES)/x11-component.mk
