#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2018, Oracle and/or its affiliates. All rights reserved.
#

BUILD_BITS =            64
include ../../../../make-rules/shared-macros.mk

COMPONENT_NAME=		xhost
COMPONENT_VERSION=	1.0.7
COMPONENT_ARCHIVE_HASH= \
	sha256:93e619ee15471f576cfb30c663e18f5bc70aca577a63d2c2c03f006a7837c29a
COMPONENT_BUGDB=        x11/xclients
COMPONENT_ANITYA_ID=	15021

COMPONENT_NAME_1=       xrefresh
COMPONENT_VERSION_1=    1.0.5
COMPONENT_SRC_1=        $(COMPONENT_NAME_1)-$(COMPONENT_VERSION_1)
COMPONENT_ARCHIVE_1=    $(COMPONENT_SRC_1).tar.bz2
COMPONENT_ARCHIVE_HASH_1=       \
    sha256:3213671b0a8a9d1e8d1d5d9e3fd86842c894dd9acc1be2560eda50bc1fb791d6
COMPONENT_ANITYA_ID_1=	14955

COMPONENT_NAME_2=       xset
COMPONENT_VERSION_2=    1.2.3
COMPONENT_SRC_2=        $(COMPONENT_NAME_2)-$(COMPONENT_VERSION_2)
COMPONENT_ARCHIVE_2=    $(COMPONENT_SRC_2).tar.bz2
COMPONENT_ARCHIVE_HASH_2=       \
    sha256:4382f4fb29b88647e13f3b4bc29263134270747fc159cfc5f7e3af23588c8063
COMPONENT_ANITYA_ID_2=	14954

COMPONENT_NAME_3=       xsetroot
COMPONENT_VERSION_3=    1.1.1
COMPONENT_SRC_3=        $(COMPONENT_NAME_3)-$(COMPONENT_VERSION_3)
COMPONENT_ARCHIVE_3=    $(COMPONENT_SRC_3).tar.bz2
COMPONENT_ARCHIVE_HASH_3=       \
    sha256:ba215daaa78c415fce11b9e58c365d03bb602eaa5ea916578d76861a468cc3d9
COMPONENT_ANITYA_ID_3=	14953

COMPONENT_NAME_4=       xrdb
COMPONENT_VERSION_4=    1.1.0
COMPONENT_SRC_4=        $(COMPONENT_NAME_4)-$(COMPONENT_VERSION_4)
COMPONENT_ARCHIVE_4=    $(COMPONENT_SRC_4).tar.bz2
COMPONENT_ARCHIVE_HASH_4=       \
    sha256:73827b6bbfc9d27ca287d95a1224c306d7053cd7b8156641698d7dc541ca565b
COMPONENT_ANITYA_ID_4=	14956

COMPONENT_NAME_5=       xrandr
COMPONENT_VERSION_5=    1.5.0
COMPONENT_SRC_5=        $(COMPONENT_NAME_5)-$(COMPONENT_VERSION_5)
COMPONENT_ARCHIVE_5=    $(COMPONENT_SRC_5).tar.bz2
COMPONENT_ARCHIVE_HASH_5=       \
    sha256:c1cfd4e1d4d708c031d60801e527abc9b6d34b85f2ffa2cadd21f75ff38151cd
COMPONENT_ANITYA_ID_5=	14957

COMPONENT_NAME_6=       xmodmap
COMPONENT_VERSION_6=    1.0.9
COMPONENT_SRC_6=        $(COMPONENT_NAME_6)-$(COMPONENT_VERSION_6)
COMPONENT_ARCHIVE_6=    $(COMPONENT_SRC_6).tar.bz2
COMPONENT_ARCHIVE_HASH_6=       \
    sha256:b7b0e5cc5f10d0fb6d2d6ea4f00c77e8ac0e847cc5a73be94cd86139ac4ac478
COMPONENT_ANITYA_ID_6=	14960

COMPONENT_NAME_7=       xprop
COMPONENT_VERSION_7=    1.2.2
COMPONENT_SRC_7=        $(COMPONENT_NAME_7)-$(COMPONENT_VERSION_7)
COMPONENT_ARCHIVE_7=    $(COMPONENT_SRC_7).tar.bz2
COMPONENT_ARCHIVE_HASH_7=       \
    sha256:9bee88b1025865ad121f72d32576dd3027af1446774aa8300cce3c261d869bc6
COMPONENT_ANITYA_ID_7=	14958

COMPONENT_NAME_8=       xgamma
COMPONENT_VERSION_8=    1.0.6
COMPONENT_SRC_8=        $(COMPONENT_NAME_8)-$(COMPONENT_VERSION_8)
COMPONENT_ARCHIVE_8=    $(COMPONENT_SRC_8).tar.bz2
COMPONENT_ARCHIVE_HASH_8=       \
    sha256:0ef1c35b5c18b1b22317f455c8df13c0a471a8efad63c89c98ae3ce8c2b222d3
COMPONENT_ANITYA_ID_8=	15022

COMPONENT_NAME_9=       xcmsdb
COMPONENT_VERSION_9=    1.0.5
COMPONENT_SRC_9=        $(COMPONENT_NAME_9)-$(COMPONENT_VERSION_9)
COMPONENT_ARCHIVE_9=    $(COMPONENT_SRC_9).tar.bz2
COMPONENT_ARCHIVE_HASH_9=       \
    sha256:e5585361bb8b6a05bb814a8d0e444ee93e0f00180881d3070aff4571e97f67c6
COMPONENT_ANITYA_ID_9=	15031

COMPONENT_NAME_10=       xinput
COMPONENT_VERSION_10=    1.6.2
COMPONENT_SRC_10=        $(COMPONENT_NAME_10)-$(COMPONENT_VERSION_10)
COMPONENT_ARCHIVE_10=    $(COMPONENT_SRC_10).tar.bz2
COMPONENT_ARCHIVE_HASH_10=       \
    sha256:3694d29b4180952fbf13c6d4e59541310cbb11eef5bf888ff3d8b7f4e3aee5c4
COMPONENT_ANITYA_ID_10=  15020

COMPONENT_NAME_11=       rgb
COMPONENT_VERSION_11=    1.0.6
COMPONENT_SRC_11=        $(COMPONENT_NAME_11)-$(COMPONENT_VERSION_11)
COMPONENT_ARCHIVE_11=    $(COMPONENT_SRC_11).tar.bz2
COMPONENT_ARCHIVE_HASH_11=       \
    sha256:bbca7c6aa59939b9f6a0fb9fff15dfd62176420ffd4ae30c8d92a6a125fbe6b0
COMPONENT_ANITYA_ID_11=	 17151

TEST_TARGET = $(NO_TESTS)

BUILD_TARGET = $(BUILD_$(MK_BITS))
INSTALL_TARGET = $(INSTALL_$(MK_BITS))

LIST = 1 2 3 4 5 6 7 8 9 10 11

define extra-target-rules
$(BUILD_DIR)/%_$(1)/.configured: SOURCE_DIR=$$(SOURCE_DIR_$(1))
endef

$(foreach n, $(LIST), \
    $(eval COMPONENT_SRC_$(n) = $(COMPONENT_NAME_$(n))-$(COMPONENT_VERSION_$(n))) \
    $(eval COMPONENT_ARCHIVE_$(n) ?= $(COMPONENT_SRC_$(n)).tar.bz2) \
    $(eval COMPONENT_ARCHIVE_URL_$(n) ?= $$(COMPONENT_ARCHIVE_URL:$$(COMPONENT_ARCHIVE)=$(COMPONENT_ARCHIVE_$(n)))) \
    $(eval BUILD_DIR_$(n) += $(BUILD_DIR_$(MK_BITS))_$(n)) \
    $(eval CONFIGURE_$(MK_BITS) += $(BUILD_DIR_$(n))/.configured) \
    $(eval BUILD_$(MK_BITS)_$(n) += $(BUILD_DIR_$(n))/.built) \
    $(eval BUILD_TARGET += $(BUILD_$(MK_BITS)_$(n))) \
    $(eval INSTALL_$(MK_BITS)_$(n) += $(BUILD_DIR_$(n))/.installed) \
    $(eval INSTALL_TARGET += $(INSTALL_$(MK_BITS)_$(n))) \
    $(eval $(call extra-target-rules,$(n))) \
)

include $(WS_MAKE_RULES)/x11-component.mk

CONFIGURE_OPTIONS += --disable-secure-rpc	# for xhost

REQUIRED_PACKAGES += system/library/math
REQUIRED_PACKAGES += x11/data/xbitmaps
REQUIRED_PACKAGES += x11/header/x11-protocols
REQUIRED_PACKAGES += x11/library/libx11
REQUIRED_PACKAGES += x11/library/libxau
REQUIRED_PACKAGES += x11/library/libxcursor
REQUIRED_PACKAGES += x11/library/libxext
REQUIRED_PACKAGES += x11/library/libxi
REQUIRED_PACKAGES += x11/library/libxinerama
REQUIRED_PACKAGES += x11/library/libxmuu
REQUIRED_PACKAGES += x11/library/libxrandr
REQUIRED_PACKAGES += x11/library/libxrender
REQUIRED_PACKAGES += x11/library/libxxf86misc
REQUIRED_PACKAGES += x11/library/libxxf86vm
