#!/usr/bin/ksh
#
# Copyright (c) 2008, 2023, Oracle and/or its affiliates.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, and/or sell copies of the Software, and to permit persons
# to whom the Software is furnished to do so, provided that the above
# copyright notice(s) and this permission notice appear in all copies of
# the Software and that both the above copyright notice(s) and this
# permission notice appear in supporting documentation.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
# OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL
# INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Except as contained in this notice, the name of a copyright holder
# shall not be used in advertising or otherwise to promote the sale, use
# or other dealings in this Software without prior written authorization
# of the copyright holder.
#
###########################################################################
#

PATH=/usr/bin:/usr/sbin

. /lib/svc/share/smf_include.sh

METHOD="$1"
case $METHOD in
    start)
	if ! is_self_assembly_boot; then
		exit $SMF_EXIT_OK
	fi
	# Continue with rest of script
	;;
    refresh)
	# Continue with rest of script
	;;
esac

for DIR in "" "/64"; do
    MAKE_CACHE="/usr/bin$DIR/gtk-query-immodules-2.0"
    MODULE_DIR="/usr/lib$DIR/gtk-2.0/2.10.0/immodules/"
    CACHE_FILE="/usr/lib$DIR/gtk-2.0/2.10.0/immodules.cache"

    if [[ ! -r "${CACHE_FILE}" ]]; then
	RESULT="no cache file"
    elif [[ "${METHOD}" == "refresh" ]]; then
	RESULT="refresh requested"
    elif [[ "${MODULE_DIR}" -nt "${CACHE_FILE}" ]] ; then
	RESULT="directory updated"
    else
	RESULT="$(find ${MODULE_DIR} -name '*.so' -newer ${CACHE_FILE})"
    fi

    if [[ -n "$RESULT" ]]; then
	print "updating/creating im modules cache file ($RESULT)"
	umask 022
	${MAKE_CACHE} --update-cache
	if [[ $? -ne 0 ]]; then
	    print "${MAKE_CACHE} exited with an error while generating the cache file ${CACHE_FILE}"
	    exit $SMF_EXIT_ERR_FATAL
	else
	    print "input method cache installed in ${CACHE_FILE}"
	fi
    fi
done

exit $SMF_EXIT_OK
