#!/usr/bin/ksh
#
# Copyright (c) 2008, 2025, Oracle and/or its affiliates.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, and/or sell copies of the Software, and to permit persons
# to whom the Software is furnished to do so, provided that the above
# copyright notice(s) and this permission notice appear in all copies of
# the Software and that both the above copyright notice(s) and this
# permission notice appear in supporting documentation.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
# OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL
# INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Except as contained in this notice, the name of a copyright holder
# shall not be used in advertising or otherwise to promote the sale, use
# or other dealings in this Software without prior written authorization
# of the copyright holder.
#
###########################################################################
#

PATH=/usr/bin:/usr/sbin

. /lib/svc/share/smf_include.sh

#
# for each architecture
#   if loader file exist
#      get the list of modules and update loaders.cache 
#      irrespective of the *.so timestamps
#   else
#      make list greater than zero
#
#   if list generate loader list
#

METHOD="$1"

case "$METHOD" in
    start)
	if ! is_self_assembly_boot; then
		exit $SMF_EXIT_OK
	fi
	# Continue with rest of script
	;;
    refresh)
        # Continue with rest of script
        ;;
esac


ARCH64=`/bin/isainfo -k`

for BITNESS in "" "$ARCH64"; do

  FILE=/usr/lib/$BITNESS/gdk-pixbuf-2.0/2.10.0/loaders.cache

  # Check if directory is writable
  if [[ ! -w "$(dirname "$FILE")" ]]; then
    echo "Error, $(dirname "$FILE") is not writable, skipping."
    continue
  fi

  # Check if file is writable
  if [[ -a "$FILE" && ! -w "$FILE" ]]; then
    echo "$FILE is not writable, skipping."
    continue
  fi

  echo "updating/creating gdk pixbuf loaders file"
  /usr/bin/$BITNESS/gdk-pixbuf-query-loaders --update-cache
  RET=$?

  /usr/bin/chown root:bin "$FILE"
  /usr/bin/chmod 0444 "$FILE"

  if [[ $RET -ne 0 ]]; then
    echo "gdk-pixbuf-query-loaders exited with an error while generating the installer file $FILE."
    exit $SMF_EXIT_ERR_FATAL
  else
    echo "gdk pixbuf loaders installed in $FILE."
  fi

done

exit $SMF_EXIT_OK
