#!/bin/bash

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2017, 2026, Oracle and/or its affiliates.
#

# Override HOME. Bash processes $HOME/.profile.
HOME=$(mktemp -d -t bash-test.XXXXXXXXX)
mkdir -p "$HOME"
export HOME

# Pre-set TMPDIR. The content of system tmp could collide with the tests.
TMPDIR="$HOME/tmp"
mkdir -p "$TMPDIR"
export TMPDIR

# Run the tests in screen. This ensures consistency between running manually in
# console and running in Phabricator where terminal is not available. Screen
# needs some pty, so create one using python. We can't run the tests directly in
# python as pty module does not simulate terminal, it merely provides pty device.
# Also we set the TERM environment variable to 'xterm' so that screen does not
# start confused setting TERM to 'dumb' which breaks the tests again. Also we
# have to collect the test output ourselves, since userland infrastructure
# captures the screen output which is full of terminal control codes. To offset
# anything user may have set in his .screenrc we use /dev/null as screen config.
# Python signal.signal installs default SIGPIPE handler which seems to break
# the tests. Last touch is to unset TSTP signal which is set if we run 'gmake
# test' via ssh. Unsetting it to default makes the tests pass even in this
# case.
python -c '
import pty;
import signal;
import sys;

signal.signal(signal.SIGPIPE, signal.SIG_DFL)
signal.signal(signal.SIGTSTP, signal.SIG_DFL)
pty.spawn(sys.argv[1:])
' env TERM=xterm /usr/bin/screen -c /dev/null bash -c 'gmake '"$@"' 2>&1 | tee outfile'
