.\"
.\" Copyright (c) 2010, 2018, Oracle and/or its affiliates. All rights reserved.
.\"
.\" Copyright (c) 1996-2001 Tobias Oetiker and all the Contributers to MRTG.  All rights reserved.
.\"
.TH mrtg-traffic-sum 1 "9 Jan 2009" "Solaris 11.4" "User Commands"
.SH NAME
mrtg-traffic-sum \- Builds monthly traffic summary
.SH SYNOPSIS
\fBmrtg-traffic-sum [options...] config-file\fR 
.sp
-h, --help      display this help and exit
.br
--version       output version information and exit
.br
--catch=regexp  filter out things that match this in PageTop
.br
--email=address email the result
.br
--min=gigabytes minimal number of gigabites required
.SH DESCRIPTION
.sp
The mrtg-traffic-sum goes through the mrtg logs for the targets in the config file specified and builds the traffic total for the last month in Giga Bytes. (Note in communications Giga is 10^9).
.sp
The result of this analysis can be sent via email to an address of your choice using the --email option.
.sp
With the --catch option you can specify a regular expression which will be matched against the contents of the PageTop settings. The regular expression should return a value into $1 and possibly into $2. This will then be used as description for the appropriate traffic sum. By default the catch is set to:
.sp
(?:description|port name):</td>\s*<td>\s*([^< ]*?[^<]*?)\s*</td
.sp
By default only traffic which is over 500 gigabytes gets reported. Use the --min switch to change this number.
.SH AUTHOR
.sp
Tobias Oetiker <tobi@oetiker.ch>
.SH SEE ALSO
.sp
\fBmrtg\fR(1), \fBmrtg-reference\fR(1), \fBmrtg-logfile\fR(1), \fBcfgmaker\fR(1), \fBindexmaker\fR(1), \fBrateup\fR(1)
