In-house patch to remove gzipping of man pages

The patch will not be sent to upstream.

--- rabbitmq-server-4.2.4/Makefile
+++ rabbitmq-server-4.2.4/Makefile
@@ -462,8 +462,8 @@ | sed -E 's/.*\.([1-9])$$/\1/' | uniq |
 	for section in $$sections; do \
 		mkdir -p $(DESTDIR)$(MANDIR)/man$$section; \
 		for manpage in $(DEPS_DIR)/rabbit/docs/*.$$section; do \
-			gzip < $$manpage \
-			 > $(DESTDIR)$(MANDIR)/man$$section/$$(basename $$manpage).gz; \
+			cp $$manpage \
+			 $(DESTDIR)$(MANDIR)/man$$section/$$(basename $$manpage); \
 		done; \
 	done
 
