'\" te
.\" Copyright (c) 1999, 2017, Oracle and/or its affiliates. All rights reserved.
.TH zoneinfo 5 "27 Oct 2015" "Solaris 11.4" "File Formats"
.SH NAME
zoneinfo \- timezone information
.SH DESCRIPTION
.sp
.LP
For notes regarding the zoneinfo timezones, see \fB/usr/share/lib/zoneinfo/src/README\fR.
