'\" te
.\" Copyright (c) 2009, 2021, Oracle and/or its affiliates.
.TH openssl 7 "8 Oct 2021" "Solaris 11.4" "Standards, Environments, and Macros"
.SH NAME
openssl \- OpenSSL cryptographic and Secure Sockets Layer toolkit
.SH DESCRIPTION
.sp
.LP
OpenSSL is a cryptography toolkit that implements the Transport Layer Security (TLS v1+) network protocols.  This version of OpenSSL no longer supports the Secure Sockets Layer (SSLv2/v3) network protocols.
.SS "The Dynamic Engine Support"
.sp
.LP
The dynamic engine support has been enabled, which allows an external engine, in the form of a shared library, to be dynamically bound and used by an OpenSSL-based application. But these functions are being deprecated in OpenSSL 3.0, and users of these APIs should know that their use can likely bypass provider selection and configuration, with unintended consequences.
.sp
.LP
Run the following command to see if the dynamic engine is supported:
.sp
.in +2
.nf
$ \fBopenssl engine dynamic\fR
(dynamic) Dynamic engine loading support
.fi
.in -2
.sp

.SS "FIPS Mode"
.sp
.LP
OpenSSL 3 uses the Provider concept. Providers collect together and make available algorithm implementations. It is  possible to specify by configuration file or programmatically, which providers you want to use in an application. One of the standard providers available is the FIPS provider. This makes available FIPS validated cryptographic algorithms.
.sp

.SS "The PKCS#11 Engine"
.sp
.LP
The PKCS#11 engine is not delivered with OpenSSL 3.
.sp

.SS "Building an OpenSSL Application"
.sp
.LP
The development files are available in the /usr/openssl/3/ sub-directories. To build an OpenSSL application, use the following \fBcc\fR command line options:
.sp
.in +2
.nf
export PKG_CONFIG_PATH=/usr/openssl/3/lib/64/pkgconfig
cc `pkg-config --cflags --libs libssl libcrypto` [ \fIflag\fR... ] \fIfile\fR
.fi
.in -2

.SS "Additional Documentation"
.sp
.LP
Extensive additional documentation for OpenSSL modules is available in the \fB/usr/openssl/3/share/man\fR sub-directories.
.sp
.LP
To view the license terms, attribution, and copyright for OpenSSL, run \fBpkg info --license library/security/openssl-3\fR.

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(7) for a description of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Availabilitylibrary/security/openssl-3
_
Interface StabilityPass-through Uncommitted
.TE

.SH SEE ALSO
.sp
.LP
\fBpkg-config\fR(1), \fBcrle\fR(1), \fBcryptoadm\fR(8), \fBattributes\fR(7), \fBprivileges\fR(7)
