Add SunOS to list or supported OSs.

--- a/Makefile.new	2024-08-15 08:12:12.299401895 +0200
+++ b/Makefile	2024-08-15 08:12:39.541836208 +0200
@@ -151,7 +151,7 @@
 #------------------------------------------------------------------------------
 # make install is validated only for Linux, macOS, Hurd and some BSD targets
 #------------------------------------------------------------------------------
-ifneq (,$(filter $(shell uname),Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD DragonFly NetBSD MSYS_NT CYGWIN_NT Haiku AIX))
+ifneq (,$(filter $(shell uname),Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD DragonFly NetBSD MSYS_NT CYGWIN_NT Haiku AIX SunOS))
 
 HOST_OS = POSIX
 
