#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2007, 2026, Oracle and/or its affiliates.
#

. /lib/svc/share/smf_include.sh

# SMF_FMRI is the name of the target service. This allows multiple instances
# to use the same script.


getproparg() {
	val=$(svcprop -p "$1" memcached)
	[ -n "$val" ] && echo "$val"
}

# memcached/options is delegated via Solaris SMF authorizations. Do not let
# delegated property values override the service account chosen by this method.
filterpropargs() {
	filtered_options=
	skip_next=false
	for option in $MCOPTIONS; do
		if [ "$skip_next" = true ]; then
			skip_next=false
			continue
		fi
		case "$option" in
		--)
			echo "Ignoring $option in memcached/options; the service runs as noaccess" >&2
			;;
		--us|--use|--user)
			echo "Ignoring $option in memcached/options; the service runs as noaccess" >&2
			skip_next=true
			;;
		--us=*|--use=*|--user=*)
			echo "Ignoring $option in memcached/options; the service runs as noaccess" >&2
			;;
		--*)
			filtered_options="$filtered_options $option"
			;;
		-*u)
			echo "Ignoring $option in memcached/options; the service runs as noaccess" >&2
			skip_next=true
			;;
		-*u*)
			echo "Ignoring $option in memcached/options; the service runs as noaccess" >&2
			;;
		*)
			filtered_options="$filtered_options $option"
			;;
		esac
	done
	MCOPTIONS="$filtered_options"
}

MCOPTIONS="$(getproparg memcached/options)"
filterpropargs

case "$1" in
'start')
/usr/lib/memcached $MCOPTIONS -u noaccess &
;;

'stop')
smf_kill_contract $2 TERM 1 
;;

*)
echo "Usage: $0 {start|stop}"
exit 1
;;

esac
#exit $SMF_EXIT_OK
