.TH junit 3 "15 Nov 2021"
.SH NAME
junit \- Java Unit testing framework
.SH SYNOPSIS
add junit.jar to the CLASSPATH
.SH DESCRIPTION
junit is a simple framework to write repeatable tests. It
is an instance of the xUnit architecture for unit testing 
frameworks. For additional information on using junit, 
browse the complete documentation at:
.IP
.B file://usr/share/doc/junit/README.html
.LP
.SH LICENSE
Common Public License 
.SH FILES
/usr/share/lib/java/junit.jar
.IP
JUnit framework jar file, bundled with the hamcrest-core-1.1 dependency.
.LP

/usr/share/doc/junit/doc/building-junit.txt
.IP
Steps to build JUnit
.LP

/usr/share/doc/junit/doc/cookbook/cookbook.htm
.IP
A cookbook for implementing tests with JUnit.
.LP

/usr/share/lib/java/javadoc/junit/index.html
.IP
API documentation generated with javadoc. 
.LP

/usr/share/doc/junit/samples
.IP
sample test cases
.LP
.PD
